- name: Download Discord .deb package
  ansible.builtin.get_url:
    url: "https://discord.com/api/download?platform=linux&format=deb"
    dest: "/tmp/discord.deb"

- name: Install Discord .deb package
  ansible.builtin.apt:
    deb: "/tmp/discord.deb"
  become: true

- name: Install betterdiscordctl
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/bb010g/betterdiscordctl/master/betterdiscordctl"
    dest: "/usr/local/bin/betterdiscordctl"
    mode: "0755"
  become: true

- name: Check if BetterDiscord is already installed
  ansible.builtin.shell: "betterdiscordctl status | grep 'injected:' | sed 's/^.*: //'"
  register: betterdiscord

- name: Install BetterDiscord if not installed
  ansible.builtin.shell: "betterdiscordctl install"
  become_user: "{{ local_user }}"
  become: true
  when: betterdiscord.stdout == "no"

- name: Update BetterDiscord if already installed
  ansible.builtin.shell: "betterdiscordctl reinstall"
  become_user: "{{ local_user }}"
  become: true
  when: betterdiscord.stdout == "yes"

- name: Create BetterDiscord theme directory
  ansible.builtin.file:
    dest: "/home/{{ local_user }}/.config/BetterDiscord/themes/"
    state: directory
    recurse: true

- name: Download BetterDiscord Catppucchin theme
  ansible.builtin.get_url:
    url: "https://github.com/catppuccin/discord/blob/main/themes/mocha.theme.css?raw=1"
    dest: "/home/{{ local_user }}/.config/BetterDiscord/themes/mocha.theme.css"

- name: Create BetterDiscord data theme directory
  ansible.builtin.file:
    dest: "/home/{{ local_user }}/.config/BetterDiscord/data/stable/"
    state: directory
    recurse: true
 
- name: Enable BetterDiscord Catppucchin theme
  ansible.builtin.copy:
    dest: "/home/{{ local_user }}/.config/BetterDiscord/data/stable/themes.json"
    content: |
      {
          "Catppuccin Mocha": true
      }

- name: Create update script
  ansible.builtin.copy:
    dest: "/usr/local/bin/discord_update.sh"
    content: |
      #!/bin/bash

      # wait until network services are available and url can be resolved
      while ! curl -ILSs "https://discord.com/api/download?platform=linux&format=deb" -o /dev/null; do
        sleep 5
      done

      TMPDIR=$(mktemp -d)

      cleanup() {
          rm -rf "$TMPDIR"
      }

      trap cleanup EXIT
      trap cleanup ERR

      installed_version=$(dpkg -s discord | grep -i '^Version' | cut -d' ' -f2)

      base_url="https://discord.com/api/download?platform=linux&format=deb"
      download_url=$(curl -w "%{url_effective}" -ILSs "$base_url" -o /dev/null)
      upstream_version=$(echo "$download_url" | grep -oP '(?<=/discord-)[0-9]+\.[0-9]+\.[0-9]+(?=\.deb)')

      higher_version=$(
          printf "%s\n" "$upstream_version" "$installed_version" \
          | sort --version-sort --reverse | head -1
      )

      if [[ $installed_version != $higher_version ]]; then
          deb_file="$TMPDIR/discord.deb"
          curl -L "$download_url" -o "$deb_file"
          dpkg -i "$deb_file"

          # update BetterDiscord
          su -c '/usr/local/bin/betterdiscordctl reinstall' {{ local_user }}
      fi
    mode: "0755"
  become: true

- name: Add update script cronjob
  ansible.builtin.cron:
    name: "Discord Update"
    special_time: reboot
    job: "/usr/local/bin/discord_update.sh"
