- name: "Install Neovim from GitHub Releases"
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
    dest: "/opt/"
    remote_src: yes
  become: true

- name: "Create Neovim symlink"
  ansible.builtin.file:
    dest: "/usr/local/bin/nvim"
    src: "/opt/nvim-linux64/bin/nvim"
    state: link
    force: yes
  become: true

- name: Install required apt packages
  ansible.builtin.apt:
    name:
      - ripgrep
      - build-essential # C compiler is needed 
      - npm
    state: latest
  become: true

- name: Update .bashrc
  block:
    - name: Check for .bashrc
      ansible.builtin.stat:
        path: "/home/{{ local_user }}/.bashrc"
      register: bashrc
      changed_when: false

    - name: Add nvim aliases to .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ local_user }}/.bashrc"
        line: "{{ item }}"
        state: present
      loop:
        - "export VISUAL=\"nvim\""
        - "export EDITOR=\"nvim\""
        - "alias vi=\"nvim\""
        - "alias vim=\"nvim\""
      when: bashrc.stat.exists

- name: Update .zshrc
  block:
    - name: Check for .zshrc
      ansible.builtin.stat:
        path: "/home/{{ local_user }}/.zshrc"
      register: zshrc
      changed_when: false

    - name: Add nvim aliases to .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ local_user }}/.zshrc"
        line: "{{ item }}"
        state: present
      loop:
        - "export VISUAL=\"nvim\""
        - "export EDITOR=\"nvim\""
        - "alias vi=\"nvim\""
        - "alias vim=\"nvim\""
      when: zshrc.stat.exists

- name: "Copy custom Neovim config"
  ansible.builtin.copy:
    src: "nvim"
    dest: "/home/{{ local_user }}/.config/"
    backup: yes

- name: "Copy custom Neovim config"
  ansible.builtin.copy:
    src: "intellij/.ideavimrc"
    dest: "/home/{{ local_user }}/.ideavimrc/"
    backup: yes

- name: "Set Neovim as default editor"
  community.general.alternatives:
    name: "editor"
    path: "/opt/nvim-linux64/bin/nvim"
  become: true
