# Install git from source as version v2.37.1+ is required for auto remote
- name: Remove git provided from Ubuntu repos
  ansible.builtin.package:
    name: git
    state: absent
  become: true

- name: Install git dependencies
  ansible.builtin.package:
    name:
      - build-essential
      - dh-autoreconf
      - libcurl4-gnutls-dev
      - libexpat1-dev
      - gettext
      - libz-dev
      - libssl-dev
      - asciidoc
      - xmlto
      - docbook2x
    state: latest
  become: true

- name: Find latest git version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/git/git/tags"
    return_content: yes
    validate_certs: no
    body_format: raw
  register: git_tags_response

- name: Set git version to latest
  ansible.builtin.set_fact:
    git_version: "{{ git_tags_response.json[0].name | replace('v', '')  }}"

- name: Create Git directory
  ansible.builtin.file:
    dest: "/opt/git"
    state: directory
    recurse: true
  become: true

- name: Expand git archive
  ansible.builtin.unarchive:
    src: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
    dest: "/opt/git"
    remote_src: yes
    mode: "0755"
  become: true

- name: Build git
  ansible.builtin.shell:
    cmd: "make prefix=/usr/local all"
    chdir: "/opt/git/git-{{ git_version }}/"
  become: true

- name: Install git
  ansible.builtin.shell:
    cmd: "make prefix=/usr/local install"
    chdir: "/opt/git/git-{{ git_version }}/"
  become: true

- name: Enable auto remote setup
  community.general.git_config:
    name: "push.autoSetupRemote"
    scope: "global"
    value: "true"

- name: Create global gitignore directory
  ansible.builtin.file:
    dest: "/home/{{ local_user }}/.config/git"
    state: directory
    recurse: true

- name: Copy global gitignore
  ansible.builtin.copy:
    src: "git/ignore"
    dest: "/home/{{ local_user }}/.config/git/ignore"
 
- name: Set global gitignore path
  community.general.git_config:
    name: "core.excludesFile"
    scope: "global"
    value: "~/.config/git/ignore"

