- name: Find latest Helm version
  ansible.builtin.uri:
    url: "https://api.github.com/repos/helm/helm/releases"
    return_content: yes
    validate_certs: no
    body_format: raw
  register: helm_releases_response

- name: Set Helm version to latest
  ansible.builtin.set_fact:
    helm_version: "{{ helm_releases_response.json[0].tag_name | replace('v', '')  }}"

- name: Create Helm directory
  ansible.builtin.file:
    dest: "/opt/helm"
    state: directory
    recurse: true
  become: true

- name: Install Helm {{ helm_version }}
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz"
    dest: "/opt/helm"
    remote_src: yes
  become: true

- name: Symlink Helm binary
  ansible.builtin.file:
    src: "/opt/helm/linux-amd64/helm"
    dest: "/usr/local/bin/helm"
    state: link
  become: true
