- name: Install KDE Plasma
  ansible.builtin.apt:
    name: kubuntu-desktop 
    state: present

- name: Install KDE applications
  ansible.builtin.apt:
    pkg:
      - kontact 
      - kmail
    state: present

- name: Create Konsole profile directory
  ansible.builtin.file:
    path: "/home/{{ local_user }}/.local/share/konsole"
    mode: "0775"
    state: directory

- name: Copy Konsole profile
  ansible.builtin.copy:
    src: "kde/konsole/dm432.profile"
    dest: "/home/{{ local_user }}/.local/share/konsole"
    mode: "0644"

- name: Download Orchis-kde theme
  ansible.builtin.git:
    repo: "https://github.com/vinceliuice/Orchis-kde"
    dest: "/tmp/Orchis-kde"
    depth: 1

- name: Install Orchis-kde theme
  ansible.builtin.shell: "/tmp/Orchis-kde/install.sh"

