- name: Install KDE Plasma
  ansible.builtin.apt:
    name: kubuntu-desktop 
    state: latest

- name: Install KDE applications
  ansible.builtin.apt:
    pkg:
      - kontact 
      - kmail
    state: latest
