- name: Install KDE Plasma
  ansible.builtin.apt:
    name: kubuntu-desktop 
    state: latest
  become: true

- name: Install KDE applications
  ansible.builtin.apt:
    name:
      - kontact 
      - kmail
    state: latest
  become: true
