- name: Install zsh apt package
  ansible.builtin.apt:
    name: zsh
    state: latest

- name: Change user's shell to zsh
  ansible.builtin.user:
    name: "{{ local_user }}"
    shell: "/bin/zsh"
  ignore_errors: true

- name: Create .zshrc file if not exists
  copy:
    content: ""
    dest: "/home/{{ local_user }}/.zshrc"
    force: false
    owner: "{{ local_user }}"
    group: "{{ local_user }}"

- name: Download zsh-autosuggestions plugin 
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "/home/{{ local_user }}/.zsh/zsh-autosuggestions"
    depth: 1

- name: Add zsh-autosuggestions plugin to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ local_user }}/.zshrc"
    line: "source \"/home/{{ local_user }}/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh\""
    state: present

- name: Download zsh-syntax-highlighting plugin 
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "/home/{{ local_user }}/.zsh/zsh-syntax-highlighting"
    depth: 1

- name: Add zsh-syntax-highlighting plugin to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ local_user }}/.zshrc"
    line: "source \"/home/{{ local_user }}/.zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh\""
    state: present

- name: Download JetBrainsMono Nerd Font
  ansible.builtin.get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/JetBrainsMono.zip"
    dest: "/tmp/JetBrainsMono.zip"
    mode: '0755'

- name: Create directory for unarchive 
  file:
    path: "/tmp/jetbrainsmono/"
    state: directory

- name: Extract JetBrainsMono Nerd Font from archive 
  ansible.builtin.unarchive:
    src: "/tmp/JetBrainsMono.zip"
    dest: "/tmp/jetbrainsmono/"
    remote_src: yes

- name: Install JetBrainsMono Nerd Fonts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/fonts/truetype/custom/"
    mode: '0755'
  with_fileglob:
    - "/tmp/jetbrainsmono/JetBrainsMonoNerdFont-*.ttf"

- name: Download starship from GitHub Releases
  ansible.builtin.get_url:
    url: "https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/starship-x86_64-unknown-linux-gnu.tar.gz"
    mode: '0755'

- name: Extract starship from archive 
  ansible.builtin.unarchive:
    src: "/tmp/starship-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Install starship binary
  ansible.builtin.copy:
    src: "/tmp/starship"
    dest: "/usr/local/bin/starship"
    mode: '0755'

- name: Add starship to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ local_user }}/.zshrc"
    line: "eval \"$(starship init zsh)\""
    state: present

- name: Copy starship configuration
  ansible.builtin.copy:
    src: "shell/starship.toml"
    dest: "/home/{{ local_user }}/.config/starship.toml"

- name: Add ll alias to .zshrc
  ansible.builtin.lineinfile:
    path: "/home/{{ local_user }}/.zshrc"
    line: "alias ll=\"ls -alF\""
    state: present
