- name: "Install Neovim from GitHub Releases"
  ansible.builtin.unarchive:
    src: "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
    dest: "/opt/"
    remote_src: yes
    owner: "root"
  become: true

- name: "Create Neovim symlink"
  ansible.builtin.file:
    dest: "/usr/local/bin/nvim"
    src: "/opt/nvim-linux64/bin/nvim"
    state: link
    force: yes

- name: Install ripgrep apt package
  ansible.builtin.apt:
    name: ripgrep
    state: present

- name: Update .bashrc
  block:
    - name: Check for .bashrc
      ansible.builtin.stat:
        path: "/home/{{ local_user }}/.bashrc"
      register: bashrc
      changed_when: false

    - name: Add nvim aliases to .bashrc
      ansible.builtin.lineinfile:
        path: "/home/{{ local_user }}/.bashrc"
        line: "{{ item }}"
        state: present
      loop:
        - "alias vi=\"nvim\""
        - "alias vim=\"nvim\""
      when: bashrc.stat.exists

- name: Update .zshrc
  block:
    - name: Check for .zshrc
      ansible.builtin.stat:
        path: "/home/{{ local_user }}/.zshrc"
      register: zshrc
      changed_when: false

    - name: Add nvim aliases to .zshrc
      ansible.builtin.lineinfile:
        path: "/home/{{ local_user }}/.zshrc"
        line: "{{ item }}"
        state: present
      loop:
        - "alias vi=\"nvim\""
        - "alias vim=\"nvim\""
      when: zshrc.stat.exists

- name: "Copy custom Neovim config"
  ansible.builtin.copy:
    src: "nvim"
    dest: "/home/{{ local_user }}/.config/"
    owner: "{{ local_user }}"
    backup: yes

- name: "Set Neovim as default editor"
  community.general.alternatives:
    name: "editor"
    path: "/opt/nvim-linux64/bin/nvim"
