- name: Add Vivaldi apt key
  ansible.builtin.apt_key:
    url: "https://repo.vivaldi.com/archive/linux_signing_key.pub"
    state: present

- name: Add Vivaldi repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://repo.vivaldi.com/archive/deb stable main
    filename: vivaldi
    state: present
  become: true

- name: Install Vivaldi
  ansible.builtin.apt:
    name: vivaldi-stable
    state: latest


