- name: Install zsh apt package
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Change user's shell to zsh
  ansible.builtin.user:
    name: "{{ local_user }}"
    shell: "/bin/zsh"

- name: Download Oh My zsh
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh.git"
    dest: "/home/{{ local_user }}/.oh-my-zsh"
    depth: 1
  
- name: Download Oh My zsh plugins
  block:
    - name: Download zsh-autosuggestions plugin 
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-autosuggestions"
        dest: "/home/{{ local_user }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
        depth: 1
    
    - name: Download zsh-completions plugin
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-completions"
        dest: "/home/{{ local_user }}/.oh-my-zsh/custom/plugins/zsh-completions"
        depth: 1
    
    - name: Download zsh-syntax-highlighting plugin
      ansible.builtin.git:
        repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
        dest: "/home/{{ local_user }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
        depth: 1

- name: Download MesloLGS NF fonts
  block:
    - name: Download MesloLGS NF Regular font
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
        dest: "/usr/share/fonts/truetype/custom"

    - name: Download MesloLGS NF Bold font
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
        dest: "/usr/share/fonts/truetype/custom"

    - name: Download MesloLGS NF Italic font
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
        dest: "/usr/share/fonts/truetype/custom"

    - name: Download MesloLGS NF Bold Italic font
      ansible.builtin.get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
        dest: "/usr/share/fonts/truetype/custom"

- name: Install Powerlevel10k theme
  ansible.builtin.git:
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "/home/{{ local_user }}/powerlevel10k"
    depth: 1

- name: "Copy .zshrc"
  ansible.builtin.copy:
    src: "zsh/.zshrc"
    dest: "/home/{{ local_user }}/.zshrc"
    owner: "{{ local_user }}"
    backup: yes

- name: "Copy .p10k.zsh"
  ansible.builtin.copy:
    src: "zsh/.p10k.zsh"
    dest: "/home/{{ local_user }}/.p10k.zsh"
    owner: "{{ local_user }}"
    backup: yes


